---
name: Net-Random-QRBG
version: 0.01
author:
  - 'Brent Garber <overlordq@gmail.com>'
abstract: Gather random data from the QRBG Service
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  IO::Socket::INET: 0
  List::Util: 0
  bytes: 0
build_requires:
  Test::More: 0
provides:
  Net::Random::QRBG:
    file: lib/Net/Random/QRBG.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
